config/routes.rb
Rails.application.routes.draw do

  get 'developer', to: 'developer#show'
  get 'developer/dashboard', to: 'developer#dashboard'
  get 'developer/settings', to: 'developer#settings'
  get 'developer/statistics', to: 'developer#statistics'
  get 'developer/api', to: 'developer#api'
  get 'developer/networks', to: 'developer#networks'
  get 'developer/money', to: 'developer#money'
  get 'developer/report', to: 'developer#report'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  post '/signup', to: 'static_pages#signup'

  get 'developer/new'
  get 'developer/edit'
  get 'developer/users'
  get 'developer/map'
  post 'developer/saveUserEdit'
  post 'developer/saveUser'
  delete 'developer/destroy'

  get 'settings/new'
  get 'settings/edit'
  get 'settings/users'
  get 'settings/map'
  post 'settings/saveUserEdit'
  post 'settings/saveUser'
  delete 'settings/destroy'

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  resources :settings

  resources :tripthru, only: []
  get '/trips_count', to: 'tripthru#trips_count'
  get '/trips_list',  to: 'tripthru#trips_list'
  get '/trips_invoice', to: 'tripthru#trips_invoice'
  get '/invoice_summary', to: 'tripthru#invoice_summary'
  get '/user_balance', to: 'tripthru#user_balance'
  get '/trip_info', to: 'tripthru#trip_info'
  get '/networks', to: 'tripthru#networks'
  post '/partnership_rules', to:'tripthru#update_partnership_rules'
  get '/partnerships', to: 'tripthru#get_partnerships'
  get '/partner_details', to: 'tripthru#get_partner_details'
  get '/user_transactions', to: 'tripthru#user_transactions'
  get '/current_balance', to: 'tripthru#current_balance'
  get '/currency_rates', to: 'tripthru#currency_rates'
  get '/aggregated_detail', to: 'tripthru#aggregated_detail'
  get '/aggregated_total', to: 'tripthru#aggregated_total'

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::SecurePassword
  has_many :products, foreign_key: 'user_id', primary_key: 'id'
  has_many :trips, foreign_key: 'user_id', primary_key: 'id'
  has_many :trips, foreign_key: 'servicing_network_id', primary_key: 'id'
  has_many :user_transactions, foreign_key: 'user_id', primary_key: 'id'

  validates(:name, :presence => true)
  has_secure_password
  validates :password_digest, length: { minimum: 6 }, :presence => true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'developer'

  def index
  end

  def new
    if roleUser == 'Admin'
      @user = User.new
    else
      redirect_to new_session_path
    end
    render :partial => 'new', :locals => {:user => User.new, :edit => false}
  end

  def saveUser
    if roleUser == 'Admin'
      user = User.new(UserName: params[:user][:UserName].downcase, password_digest: BCrypt::Password.create(params[:user][:password_digest]), Email: params[:user][:Email].downcase, Role: params[:user][:Role])
      if user.Role == 'Partner'
        user.PartnerName=params[:user][:PartnerName]
        user.CallbackUrl=params[:user][:CallbackUrl]
        user.TripThruAccessToken=params[:user][:TripThruAccessToken]
      end
      o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
      c = (0...50).map { o[rand(o.length)] }.join
      user.RefreshToken=c
      o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
      c = (0...50).map { o[rand(o.length)] }.join
      user.AccessToken=c
      user.save
      if user.valid?
        redirect_to users_users_path
      else
        redirect_to users_new_path
      end
    else
      redirect_to session_path
    end

  end

  def users
    if roleUser == 'Admin'
      @users = User.all
    else
      redirect_to new_session_path
    end
  end

  def edit
    if roleUser == 'Admin'
      user = User.find(params[:id])
      render :partial => 'new', :locals => {:user => user, :edit => true}
    else
      redirect_to session_path
    end
  end

  def update
    if roleUser == 'Admin'
      user = User.find_by_UserName(params[:user][:UserName])
      user.password_digest = BCrypt::Password.create(params[:user][:password_digest])
      user.Email = params[:user][:Email]
      user.Role = params[:user][:Role]
      user.PartnerName = params[:user][:PartnerName]
      user.CallbackUrl = params[:user][:CallbackUrl]
      user.TripThruAccessToken = params[:user][:TripThruAccessToken]
      user.save
      redirect_to users_users_path
    else
      redirect_to session_path
    end

  end

  def destroy
    if roleUser == 'Admin'
      User.find(params[:id]).delete
      redirect_to users_users_path
    else
      redirect_to session_path
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<% if edit %>
    <% urlUser = users_saveUserEdit_path %>
<% else %>
    <% urlUser = users_saveUser_path %>
<% end %>
<%= form_for(user, url: urlUser) do |f| %>
    <%= f.label :Username %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-user"></span>
      <% if edit %>
          <%= f.text_field :UserName, class: 'form-control ', placeholder: 'Username', required: true, readonly: true %>
      <% else %>
          <%= f.text_field :UserName, class: 'form-control ', placeholder: 'Username', required: true %>
      <% end %>
    </div>
    <br/>
    <%= f.label :Password %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
      <%= f.password_field :password_digest, class: 'form-control', placeholder: 'Password', required: true %>
    </div>
    <br/>
    <%= f.label :Repeat_Password %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
      <%= f.password_field :Repeat_Password, class: 'form-control', placeholder: 'Repeat Password', :onkeyup => 'checkPass();', required: true %>
    </div>
    <span id="confirmMessage" class="confirmMessage"></span>
    <br/>
    <%= f.label :Email %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-envelope"></span>
      <%= f.text_field :Email, class: 'form-control', placeholder: 'example@example.com', required: true %>
    </div>
    <br/>
    <%= f.label :Role %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-tags"></span>
      <%= f.select :Role, options_for_select([%w(Partner Partner), %w(Demo Demo), %w(Admin Admin)], :selected => (user.Role.nil? ? 'Partner' : user.Role)), class: 'form-control ', required: true %>
    </div>
    <br/>
    <%= f.label :Partner_Name, id: 'user_Partner_Name' %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-certificate" id="icon_Partner_Name"></span>
      <%= f.text_field :PartnerName, class: 'form-control', placeholder: 'Partner Name', required: true %>
    </div>
    <br/>
    <%= f.label :Callback_Url, id: 'user_Callback_Url' %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-globe" id="icon_Callback_Url"></span>
      <%= f.url_field :CallbackUrl, class: 'form-control', placeholder: 'www.example.com', required: true %>
    </div>
    <br/>
    <%= f.label :TripThru_AccessToken, id: 'user_TripThru_AccessToken' %>
    <div class="input-group col-md-12">
      <span class="input-group-addon glyphicon glyphicon-barcode" id="icon_TripThru_AccessToken"></span>
      <%= f.text_field :TripThruAccessToken, class: 'form-control', placeholder: 'Token', required: true %>
    </div>
    <br/>
    <% if edit %>
        <%= f.submit "Update", class: "btn btn-large btn-primary", align: 'center', id: 'button' %>
    <% else %>
        <%= f.submit "Create", class: "btn btn-large btn-primary", align: 'center', id: 'button' %>
    <% end %>
<% end %>
<script type="text/javascript">
    function changeValue() {
        var e = document.getElementById("user_Role");
        var strUser = e.options[e.selectedIndex].text;
        if (strUser == 'Partner') {
            var partnerNameId = document.getElementById("user_PartnerName");
            partnerNameId.setAttribute("required", "required");
            partnerNameId.removeAttribute("type");
            document.getElementById("icon_Partner_Name").style.display = "block";
            document.getElementById("user_Partner_Name").style.display = "inline";
            var callbackUrlId = document.getElementById("user_CallbackUrl");
            callbackUrlId.setAttribute("required", "required");
            callbackUrlId.removeAttribute("type");
            document.getElementById("user_Callback_Url").style.display = "inline";
            document.getElementById("icon_Callback_Url").style.display = "block";
            var tripthruAccesstokenId = document.getElementById("user_TripThruAccessToken");
            tripthruAccesstokenId.setAttribute("required", "required");
            tripthruAccesstokenId.removeAttribute("type");
            document.getElementById("user_TripThru_AccessToken").style.display = "inline";
            document.getElementById("icon_TripThru_AccessToken").style.display = "block";
        } else {
            var partnerNameId = document.getElementById("user_PartnerName");
            partnerNameId.removeAttribute("required");
            partnerNameId.setAttribute("type", "hidden");
            document.getElementById("user_Partner_Name").style.display = "none";
            document.getElementById("icon_Partner_Name").style.display = "none";
            var callbackUrlId = document.getElementById("user_CallbackUrl");
            callbackUrlId.removeAttribute("required");
            callbackUrlId.setAttribute("type", "hidden");
            document.getElementById("user_Callback_Url").style.display = "none";
            document.getElementById("icon_Callback_Url").style.display = "none";
            var tripthruAccesstokenId = document.getElementById("user_TripThruAccessToken");
            tripthruAccesstokenId.removeAttribute("required");
            tripthruAccesstokenId.setAttribute("type", "hidden");
            document.getElementById("user_TripThru_AccessToken").style.display = "none";
            document.getElementById("icon_TripThru_AccessToken").style.display = "none";
        }
    }
    var roleType = document.getElementById('user_Role');
    var handler = function () {
        if (this.value == 'Partner') {
            var partnerNameId = document.getElementById("user_PartnerName");
            partnerNameId.setAttribute("required", "required");
            partnerNameId.removeAttribute("type");
            document.getElementById("icon_Partner_Name").style.display = "block";
            document.getElementById("user_Partner_Name").style.display = "inline";
            var callbackUrlId = document.getElementById("user_CallbackUrl");
            callbackUrlId.setAttribute("required", "required");
            callbackUrlId.removeAttribute("type");
            document.getElementById("user_Callback_Url").style.display = "inline";
            document.getElementById("icon_Callback_Url").style.display = "block";
            var tripthruAccesstokenId = document.getElementById("user_TripThruAccessToken");
            tripthruAccesstokenId.setAttribute("required", "required");
            tripthruAccesstokenId.removeAttribute("type");
            document.getElementById("user_TripThru_AccessToken").style.display = "inline";
            document.getElementById("icon_TripThru_AccessToken").style.display = "block";
        } else {
            var partnerNameId = document.getElementById("user_PartnerName");
            partnerNameId.removeAttribute("required");
            partnerNameId.setAttribute("type", "hidden");
            document.getElementById("user_Partner_Name").style.display = "none";
            document.getElementById("icon_Partner_Name").style.display = "none";
            var callbackUrlId = document.getElementById("user_CallbackUrl");
            callbackUrlId.removeAttribute("required");
            callbackUrlId.setAttribute("type", "hidden");
            document.getElementById("user_Callback_Url").style.display = "none";
            document.getElementById("icon_Callback_Url").style.display = "none";
            var tripthruAccesstokenId = document.getElementById("user_TripThruAccessToken");
            tripthruAccesstokenId.removeAttribute("required");
            tripthruAccesstokenId.setAttribute("type", "hidden");
            document.getElementById("user_TripThru_AccessToken").style.display = "none";
            document.getElementById("icon_TripThru_AccessToken").style.display = "none";
        }
    };
    roleType.onchange = handler;
    function checkPass() {
        var pass1 = document.getElementById('user_password_digest');
        var pass2 = document.getElementById('user_Repeat_Password');
        var message = document.getElementById('confirmMessage');
        var goodColor = "#66cc66";
        var badColor = "#ff6666";
        if (pass1.value == pass2.value) {
            pass2.style.backgroundColor = goodColor;
            message.style.color = goodColor;
            message.innerHTML = "Passwords Match!"
            document.getElementById("button").disabled = false;
        } else {
            pass2.style.backgroundColor = badColor;
            message.style.color = badColor;
            message.innerHTML = "Passwords Do Not Match!"
            document.getElementById("button").disabled = true;
        }
    }
    changeValue();
</script>

app/views/users/users.html.erb
<div id="users">
  <div class="page-header">
    <h3>Accounts</h3>
  </div>
  <div class="container">
      <div class="panel panel-default col-md-12">
        <div class="panel-body col-md-12">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
              <tr>
                <th class="success">Id</th>
                <th class="success">User Name</th>
                <th class="success">Email</th>
                <th class="success">AccessToken</th>
                <th class="success">RefreshToken</th>
                <th class="success">PartnerName</th>
                <th class="success">CallbackUrl</th>
                <th class="success">TripThruAccessToken</th>
                <th class="success">Role</th>
                <th class="danger">Options</th>
                <th class="danger"></th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.id %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.UserName %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.Email %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.AccessToken.truncate(10) %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.RefreshToken.truncate(10) %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.PartnerName %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.CallbackUrl %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.TripThruAccessToken %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)"><%= user.Role %></td>
                    <td class="active" onclick="loadPage(<%= user.id %>)">Edit</td>
                    <td class="active"><%= link_to 'Delete', users_destroy_path(@user, :id => user.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                  </tr>
                  <br/>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="container">
          <button id="new-user-button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" onclick="loadPageNew()">
            Add New User
          </button>
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h2 class="modal-title" id="myModalLabel" align="center">Add New User</h2>
                </div>
                <div class="modal-body">
                  <div id="contenthere"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<script type="text/javascript">
    function loadPageNew() {
        $("#contenthere").load('<%= users_new_path %>');
    }
    function loadPage(id) {
        url = "<%= users_edit_path%>" + "?id=" + id;
        $("#contenthere").load(url);
        $("#myModal").modal("show");
    }
</script>