config/routes.rb
Rails.application.routes.draw do

  get 'developer', to: 'developer#show'
  get 'developer/dashboard', to: 'developer#dashboard'
  get 'developer/settings', to: 'developer#settings'
  get 'developer/statistics', to: 'developer#statistics'
  get 'developer/api', to: 'developer#api'
  get 'developer/networks', to: 'developer#networks'
  get 'developer/money', to: 'developer#money'
  get 'developer/report', to: 'developer#report'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  post '/signup', to: 'static_pages#signup'

  get 'developer/new'
  get 'developer/edit'
  get 'developer/users'
  get 'developer/map'
  post 'developer/saveUserEdit'
  post 'developer/saveUser'
  delete 'developer/destroy'

  get 'settings/new'
  get 'settings/edit'
  get 'settings/users'
  get 'settings/map'
  post 'settings/saveUserEdit'
  post 'settings/saveUser'
  delete 'settings/destroy'

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  resources :settings

  resources :tripthru, only: []
  get '/trips_count', to: 'tripthru#trips_count'
  get '/trips_list',  to: 'tripthru#trips_list'
  get '/trips_invoice', to: 'tripthru#trips_invoice'
  get '/invoice_summary', to: 'tripthru#invoice_summary'
  get '/user_balance', to: 'tripthru#user_balance'
  get '/trip_info', to: 'tripthru#trip_info'
  get '/networks', to: 'tripthru#networks'
  post '/partnership_rules', to:'tripthru#update_partnership_rules'
  get '/partnerships', to: 'tripthru#get_partnerships'
  get '/partner_details', to: 'tripthru#get_partner_details'
  get '/user_transactions', to: 'tripthru#user_transactions'
  get '/current_balance', to: 'tripthru#current_balance'
  get '/currency_rates', to: 'tripthru#currency_rates'
  get '/aggregated_detail', to: 'tripthru#aggregated_detail'
  get '/aggregated_total', to: 'tripthru#aggregated_total'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  layout 'developer'

  def index
  end

  def new
    if roleUser == 'admin'
      @user = User.new
    else
      redirect_to new_session_path
    end
    render :partial => 'new', :locals => {:user => User.new, :edit => false}
  end

  def saveUser
    if roleUser == 'admin'
      user = User.new(name: params[:user][:name].downcase, full_name: params[:user][:full_name], password_digest: BCrypt::Password.create(params[:user][:password_digest]), email: params[:user][:email].downcase, role: params[:user][:role])
      user.client_id = params[:user][:name].downcase + '@tripthru.com'
      o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
      c = (0...50).map { o[rand(o.length)] }.join
      user.token = c
      user.save
      if user.valid?
        redirect_to settings_users_path
      else
        redirect_to settings_new_path
      end
    else
      redirect_to session_path
    end

  end

  def users
    if roleUser == 'admin'
      @users = User.all
    else
      redirect_to new_session_path
    end
  end

  def edit
    if roleUser == 'admin'
      user = User.find(params[:id])
      render :partial => 'new', :locals => {:user => user, :edit => true}
    else
      redirect_to session_path
    end
  end

  def update
    if roleUser == 'admin'
      name = params[:user][:name]
      user = User.where(name: name).first
      user.password_digest = BCrypt::Password.create(params[:user][:password_digest])
      user.full_name = params[:user][:full_name]
      user.email = params[:user][:email]
      user.role = params[:user][:role]
      user.save
      redirect_to settings_users_path
    else
      redirect_to session_path
    end

  end

  def destroy
    if roleUser == 'admin'
      User.find(params[:id]).delete
      redirect_to settings_users_path
    else
      redirect_to session_path
    end

  end

  def map

  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_new.html.erb
<% if edit %>
    <% urlUser = settings_saveUserEdit_path %>
<% else %>
    <% urlUser = settings_saveUser_path %>
<% end %>
<%= form_for(user, url: urlUser) do |f| %>
    <%= f.label :name %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-user"></span>
      <% if edit %>
          <%= f.text_field :name, class: 'form-control ', placeholder: 'Username', required: true, readonly: true %>
      <% else %>
          <%= f.text_field :name, class: 'form-control ', placeholder: 'Username', required: true %>
      <% end %>
    </div>
    <br/>
    <%= f.label :full_name %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-user"></span>
      <% if edit %>
        <%= f.text_field :full_name, class: 'form-control ', placeholder: 'Full name', required: true %>
      <% else %>
        <%= f.text_field :full_name, class: 'form-control ', placeholder: 'Full name', required: true %>
      <% end %>
    </div>
    <br/>
    <%= f.label :password %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
      <%= f.password_field :password_digest, class: 'form-control', placeholder: 'Password', required: true %>
    </div>
    <br/>
    <%= f.label :repeat_password %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
      <%= f.password_field :repeat_password, class: 'form-control', placeholder: 'Repeat Password', :onkeyup => 'checkPass();', required: true %>
    </div>
    <span id="confirmMessage" class="confirmMessage"></span>
    <br/>
    <%= f.label :email %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-envelope"></span>
      <%= f.text_field :email, class: 'form-control', placeholder: 'example@example.com', required: true %>
    </div>
    <br/>
    <%= f.label :role %>
    <div class="input-group col-xs-12">
      <span class="input-group-addon glyphicon glyphicon-tags"></span>
      <%= f.select :role, options_for_select([%w(Network network), %w(Demo demo), %w(Admin admin)], :selected => (user.role.nil? ? 'network' : user.role)), class: 'form-control ', required: true %>
    </div>
    <br/>
    <% if edit %>
        <%= f.submit "Update", class: "btn btn-large btn-primary", align: 'center', id: 'button' %>
    <% else %>
        <%= f.submit "Create", class: "btn btn-large btn-primary", align: 'center', id: 'button' %>
    <% end %>
<% end %>
<script type="text/javascript">
    function checkPass() {
        var pass1 = document.getElementById('user_password_digest');
        var pass2 = document.getElementById('user_Repeat_Password');
        var message = document.getElementById('confirmMessage');
        var goodColor = "#66cc66";
        var badColor = "#ff6666";
        if (pass1.value == pass2.value) {
            pass2.style.backgroundColor = goodColor;
            message.style.color = goodColor;
            message.innerHTML = "Passwords Match!"
            document.getElementById("button").disabled = false;
        } else {
            pass2.style.backgroundColor = badColor;
            message.style.color = badColor;
            message.innerHTML = "Passwords Do Not Match!"
            document.getElementById("button").disabled = true;
        }
    }
</script>

app/views/settings/users.html.erb
<div id="users">
  <div class="container">
    <div class="row">
      <div class="panel panel-default col-md-12">
        <div class="panel-body col-md-12">
        </div>
       </div>
    </div>
    <div class="row">
      <div class="panel panel-default col-md-12">
        <div class="panel-body col-md-12">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
              <tr>
                <th class="success">Client id</th>
                <th class="success">Name</th>
                <th class="success">Email</th>
                <th class="success">Token</th>
                <th class="success">Role</th>
                <th class="danger">Options</th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td class="active" onclick="loadPage('<%= user.id %>')"><%= user.client_id %></td>
                    <td class="active" onclick="loadPage('<%= user.id %>')"><%= user.name %></td>
                    <td class="active" onclick="loadPage('<%= user.id %>')"><%= user.email %></td>
                    <td class="active" onclick="loadPage('<%= user.id %>')"><%= user.token.truncate(30) %></td>
                    <td class="active" onclick="loadPage('<%= user.id %>')"><%= user.role %></td>
                    <td class="active"><%= link_to 'Delete', settings_destroy_path(@user, :id => user.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="container">
          <button id="new-user-button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" onclick="loadPageNew()">
            Add New User
          </button>
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h2 id="headerText" class="modal-title" id="myModalLabel" align="center"></h2>
                </div>
                <div class="modal-body">
                  <div id="contenthere"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<input type="hidden" id="access_token" value="<%= userAccessToken %>"/>
<script type="text/javascript">
    function loadPageNew() {
        $('#headerText').html('Add New User');
        $("#contenthere").load('<%= settings_new_path %>');
    }
    function loadPage(id) {
        $('#headerText').html('Edit User');
        url = "<%= settings_edit_path%>" + "?id=" + id;
        $("#contenthere").load(url);
        $("#myModal").modal("show");
    }
</script>