config/routes.rb
Rails.application.routes.draw do

  get 'developer', to: 'developer#show'
  get 'developer/dashboard', to: 'developer#dashboard'
  get 'developer/settings', to: 'developer#settings'
  get 'developer/statistics', to: 'developer#statistics'
  get 'developer/api', to: 'developer#api'
  get 'developer/networks', to: 'developer#networks'
  get 'developer/money', to: 'developer#money'
  get 'developer/report', to: 'developer#report'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  post '/signup', to: 'static_pages#signup'

  get 'developer/new'
  get 'developer/edit'
  get 'developer/users'
  get 'developer/map'
  post 'developer/saveUserEdit'
  post 'developer/saveUser'
  delete 'developer/destroy'

  get 'settings/new'
  get 'settings/edit'
  get 'settings/users'
  get 'settings/map'
  post 'settings/saveUserEdit'
  post 'settings/saveUser'
  delete 'settings/destroy'

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  resources :settings

  resources :tripthru, only: []
  get '/trips_count', to: 'tripthru#trips_count'
  get '/trips_list',  to: 'tripthru#trips_list'
  get '/trips_invoice', to: 'tripthru#trips_invoice'
  get '/invoice_summary', to: 'tripthru#invoice_summary'
  get '/user_balance', to: 'tripthru#user_balance'
  get '/trip_info', to: 'tripthru#trip_info'
  get '/networks', to: 'tripthru#networks'
  post '/partnership_rules', to:'tripthru#update_partnership_rules'
  get '/partnerships', to: 'tripthru#get_partnerships'
  get '/partner_details', to: 'tripthru#get_partner_details'
  get '/user_transactions', to: 'tripthru#user_transactions'
  get '/current_balance', to: 'tripthru#current_balance'
  get '/currency_rates', to: 'tripthru#currency_rates'
  get '/aggregated_detail', to: 'tripthru#aggregated_detail'
  get '/aggregated_total', to: 'tripthru#aggregated_total'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=visualization,drawing"></script>
  <script type="text/javascript" language="javascript">
    var tl813v = 27286;
    (function() {
      var tl813 = document.createElement('script'); tl813.type = 'text/javascript'; tl813.async = true;
      tl813.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '1.tl813.com/tl813.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tl813, s);
    })();
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-bold" data-spy="affix" data-offset-top="1000">
      <div class="container">
        <div class="navbar-header">
          <a href="<%= root_path %>" class="navbar-brand logo"></a>
          <a href="#" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        </div>
        <div class="navbar-collapse collapse pull-right" id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Features', home_path+'#sec2' %></li>
            <li><%= link_to 'Contact', home_path+'#sec4' %></li>
            <li><%= link_to 'FAQ', faq_path %></li>
            <li><%= link_to 'Demo', developer_path %></li>
            <li><%= link_to 'About us', about_path %></li>
            <li><%= link_to 'Blog', 'http://blog.tripthru.com' %></li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <hr>
            <p>Copyright ©2015 TripThru, Inc. All Rights Reserved</p>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>

app/views/layouts/developer.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title('Developer') %></title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=visualization,drawing"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
    <div id="developer">

      <div id="header" class="navbar navbar-default navbar-fixed-top">
          <a href="<%= root_path %>" class="navbar-brand white-logo"></a>
          <ul class="nav navbar-nav navbar-user navbar-right">
            <li class="dropdown">
              <a href="#" id="icon-user" class="dropdown-toggle cursor pull-right" data-toggle="dropdown">
                <i class="fa fa-user"></i> <i id="getUserName"><%= user_Name %></i> <i hidden id="getUserRole"><%=roleUser%></i> <i hidden id="getUserId"><%=userId%></i> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu pull-right">
                <li><%= link_to 'Log out', signout_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
      </div>

        <div id="wrapper">
            <div id="sidebar-wrapper" class="col-md-0">
              <div id="sidebar">
                <ul class="nav list-group" id="developer-menu">
                  <li>
                    <a class="list-group-item" id="tracking-button" href="<%= developer_dashboard_path  %>">
                      <i class="icon-home icon-1x"></i>
                      <div class="image-wrapper">
                        <%= image_tag('dashboard.png', alt: 'Dashboard') %>
                      </div>
                    </a>
                  </li>
                  <% if experimentalFeaturesEnabled %>
                    <li>
                      <a class="list-group-item" id="statistics-button" href="<%= developer_statistics_path %>">
                        <i class="icon-home icon-1x"></i>
                        <div class="image-wrapper">
                          <%= image_tag('statistics.png', alt: 'Statistics') %>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a class="list-group-item" id="networks-button" href="<%= developer_networks_path %>">
                        <i class="icon-home icon-1x"></i>
                        <div class="image-wrapper">
                          <%= image_tag('networks.png', alt: 'Networks') %>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a class="list-group-item" id="networks-button" href="<%= developer_money_path %>">
                        <i class="icon-home icon-1x"></i>
                        <div class="image-wrapper">
                          <%= image_tag('money.png', alt: 'Money') %>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a class="list-group-item" id="report-button" href="<%= developer_report_path %>">
                        <i class="icon-home icon-1x"></i>
                        <div class="image-wrapper">
                          <%= image_tag('report.png', alt: 'Report') %>
                        </div>
                      </a>
                    </li>
                  <% end %>
                  <li>
                    <a class="list-group-item" id="api-button" href="<%= developer_api_path %>">
                      <i class="icon-home icon-1x"></i>
                      <div class="image-wrapper">
                        <%= image_tag('api.png', alt: 'API', style: 'margin-top: -1px;') %>
                      </div>
                    </a>
                  </li>
                  <% if experimentalFeaturesEnabled %>
                    <li>
                      <% if roleUser == 'admin' %>
                          <% url = settings_users_path %>
                      <% else %>
                          <% url = developer_settings_path %>
                      <% end %>
                      <a class="list-group-item" id="settings-button" href="<%= url %>">
                        <i class="icon-home icon-1x"></i>
                        <div class="image-wrapper">
                          <%= image_tag('settings.png', alt: 'Settings') %>
                        </div>
                      </a>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div id="main-wrapper" class="col-md-11">
              <div id="main">
                <%= yield %>
              </div>
            </div>
            <input type="hidden" id="access_token" value="<%= userAccessToken %>"/>
            <input type="hidden" id="user_role" value="<%= roleUser %>"/>
            <input type="hidden" id="user_id" value="<%= userId %>"/>
            <input type="hidden" id="user_client_id" value="<%= userClientId %>"/>
        </div>
    </div>
</body>
</html>